server:
  port: 8080
  servlet:
    context-path: /nasa

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/nasa_app"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: /templates/
      suffix: .html

nasa:
  api:
    key: W19tGHYFrWyQW1saJvLZ5OsA7zxPEOT7J4pIYSUd
