server:
  port: 8080
  servlet:
    context-path: /management

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/blog_management"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: /templates/
      suffix: .html